// @ts-nocheck
import React from "react";
import "./style.css";

const SVGIcons = () => {
  return (
    <div hidden className="svg-icons-container">
      <svg
        xmlns="http://www.w3.org/2000/svg"
        xmlnsXlink="http://www.w3.org/1999/xlink"
      >
        <symbol id="spinner-small" preserveAspectRatio="xMidYMid">
          <circle
            cx="50"
            cy="50"
            r="12"
            strokeWidth="3"
            stroke="#ff5722"
            strokeDasharray="18.84955592153876 18.84955592153876"
            fill="none"
            strokeLinecap="round"
          >
            <animateTransform
              attributeName="transform"
              type="rotate"
              dur="1s"
              repeatCount="indefinite"
              keyTimes="0;1"
              values="0 50 50;360 50 50"
            />
          </circle>
          <circle
            cx="50"
            cy="50"
            r="8"
            strokeWidth="3"
            stroke="#e6e6e6"
            strokeDasharray="12.566370614359172 12.566370614359172"
            strokeDashoffset="12.566370614359172"
            fill="none"
            strokeLinecap="round"
          >
            <animateTransform
              attributeName="transform"
              type="rotate"
              dur="1s"
              repeatCount="indefinite"
              keyTimes="0;1"
              values="0 50 50;-360 50 50"
            />
          </circle>
        </symbol>
        <symbol
          id="spinner-large"
          viewBox="0 0 100 100"
          preserveAspectRatio="xMidYMid"
        >
          <circle
            cx="50"
            cy="50"
            r="25"
            strokeWidth="3"
            stroke="#ff5722"
            strokeDasharray="39.269908169872416 39.269908169872416"
            fill="none"
            strokeLinecap="round"
          >
            <animateTransform
              attributeName="transform"
              type="rotate"
              dur="1.5384615384615383s"
              repeatCount="indefinite"
              keyTimes="0;1"
              values="0 50 50;360 50 50"
            />
          </circle>
          <circle
            cx="50"
            cy="50"
            r="21"
            strokeWidth="3"
            stroke="#e6e6e6"
            strokeDasharray="32.98672286269283 32.98672286269283"
            strokeDashoffset="32.98672286269283"
            fill="none"
            strokeLinecap="round"
          >
            <animateTransform
              attributeName="transform"
              type="rotate"
              dur="1.5384615384615383s"
              repeatCount="indefinite"
              keyTimes="0;1"
              values="0 50 50;-360 50 50"
            />
          </circle>
        </symbol>
        {/*
                        [ldio] generated by https://loading.io/
                    */}
      </svg>
    </div>
  );
};

export default SVGIcons;
